import bio from "../imgs/bio.png";
import man from "../imgs/man.png";
import ene from "../imgs/energy.png";
import ai from "../imgs/ai.png";
import food from "../imgs/food.png";
import def from "../imgs/def.png";
import pharma from "../imgs/pharma.png";
import climate from "../imgs/climate.png";
import infra from "../imgs/industry.png";
export const cardVar = [
  {
    label: "Biomedical Engineering",
    bg: "hover:from-cyan-400 hover:to-blue-300",
    card: "from-cyan-100 to-blue-200 hover:to-blue-300",
    img: bio,
    prof: [
      {
        name: "Dhiraj Bhatia",
        link: "https://iitgn.ac.in/faculty/bioe/fac-dhiraj",
        img: "https://iitgn.ac.in/media/pages/faculty/bioe/fac-dhiraj/396853053-1679554160/dhiraj.JPG",
        designation: "Associate Professor",
        dept: "Biological Engineering",
        email: "dhiraj.bhatia@iitgn.ac.in",
        hash: "hOc8bPcRKSxbzWa9uGsM",
      },
      {
        name: "Jhuma Saha",
        link: "https://iitgn.ac.in/faculty/ee/fac-jhuma",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-jhuma/2070282905-1679554160/jhuma.jpg",
        designation: "Assistant Professor",
        dept: "Electrical Engineering",
        email: "jhuma.saha@iitgn.ac.in",
        hash: "9TF4BN84JqnXPlxvz0O2",
      },
      {
        name: "Sharad Gupta",
        link: "https://iitgn.ac.in/faculty/bioe/fac-sharad",
        img: "https://iitgn.ac.in/media/pages/faculty/bioe/fac-sharad/682033906-1685685855/sharad.jpg",
        designation: "Associate Professor",
        dept: "Biological Engineering",
        email: "sharad@iitgn.ac.in",
        hash: "opHQ6d54TvlR9EBbMi5K",
      },
      {
        name: "Karla Mercado-Shekhar",
        link: "https://www.iitgn.ac.in/faculty/bioe/fac-karla",
        img: "https://www.iitgn.ac.in/media/pages/faculty/bioe/fac-karla/2108285146-1679554160/karla.jpg",
        designation: "Assistant Professor",
        dept: "Biological Engineering",
        email: "karlamshekhar@iitgn.ac.in",
        hash: "G86F5Afz3mwv6MtADYQv",
      },
      {
        name: "Himanshu Shekhar",
        link: "https://www.iitgn.ac.in/faculty/ee/fac-himanshu",
        img: "https://www.iitgn.ac.in/media/pages/faculty/ee/fac-himanshu/623112002-1679554160/himanshu.jpg",
        designation: "Assistant Professor",
        dept: "Electrical Engineering",
        email: "himanshu.shekhar@iitgn.ac.in",
      },
      {
        name: "Prachi Thareja",
        link: "https://iitgn.ac.in/faculty/chemical/fac-prachi",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-prachi/3829953309-1679554160/prachi.jpg",
        designation: "Associate Professor",
        dept: "Chemical Engineering",
        email: "prachi@iitgn.ac.in",
        hash: "WGkLwkHeKdre5O65CYjJ",
      },
      {
        name: "Pratik Mutha",
        link: "https://iitgn.ac.in/faculty/bioe/fac-pratik",
        img: "https://iitgn.ac.in/media/pages/faculty/bioe/fac-pratik/78470844-1679554160/prateek.JPG",
        designation: "Associate Professor",
        dept: "Biological Engineering",
        email: "pm@iitgn.ac.in",
      },
      {
        name: "Sameer Dalvi",
        link: "https://iitgn.ac.in/hi/faculty/chemical/fac-sameer",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-sameer/1678405332-1679554160/1sameer.jpg",
        designation: "Professor",
        dept: "Chemical Engineering",
        email: "sameervd@iitgn.ac.in",
        hash: "QyWigXd5HhFaeYXMMjIx",
      },
      {
        name: "Abhijit Mishra",
        link: "https://iitgn.ac.in/faculty/mse/fac-abhijit",
        img: "https://iitgn.ac.in/media/pages/faculty/mse/fac-abhijit/4076577973-1679554159/abhijit.jpg",
        designation: "Associate Professor",
        dept: "Materials Engineering",
        email: "amishra@iitgn.ac.in",
        hash: "yEj2mQyPcznq1nFu04gU",
      },
      {
        name: "Krishna Kanti Dey",
        link: "https://iitgn.ac.in/faculty/phy/fac-krishna",
        img: "https://iitgn.ac.in/media/pages/faculty/phy/fac-krishna/1778184909-1679554160/Krishna.jpg",
        designation: "Assistant Professor",
        dept: "Physics",
        email: "k.dey@iitgn.ac.in",
        hash: "HiJQX1sEouWkSJVHuC5W",
      },
      {
        name: "Mithun Radhakrishnan",
        link: "https://iitgn.ac.in/faculty/chemical/fac-mithun",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-mithun/3038658947-1679554160/mithun.JPG",
        designation: "Assistant Professor",
        dept: "Chemical Engineering",
        email: "mithunr@iitgn.ac.in",
      },
      {
        name: "Madhu Vadali",
        link: "https://iitgn.ac.in/faculty/ee/fac-madhu",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-madhu/2464874874-1679554160/madhu.JPG",
        designation: "Assistant Professor",
        dept: "Electrical Engineering (Jointly with Mechanical Engineering)",
        email: "madhu.vadali@iitgn.ac.in",
        hash: "yJhVsNZmSPanaJynyv9D",
      },
      {
        name: "Nipun Batra",
        link: "https://iitgn.ac.in/faculty/cse/nipun",
        img: "https://iitgn.ac.in/media/pages/faculty/cse/nipun/3587009419-1679554159/nipun.jpg",
        designation: "Assistant Professor",
        dept: "Computer Science & Engineering",
        email: "nipun.batra@iitgn.ac.in",
        hash: "3bfPAe8GjWbOPuh47uCk",
      },
      {
        name: "Sivapriya Kirubakaran",
        link: "https://iitgn.ac.in/faculty/chemistry/fac-sivapriya",
        img: "https://iitgn.ac.in/media/pages/faculty/chemistry/fac-sivapriya/556837850-1679554159/sivapriya.png",
        designation: "Associate Professor",
        dept: "Chemistry",
        email: "priyak@iitgn.ac.in",
        hash: "o4DcAf8PEsOilO5i9baY",
      },
      {
        name: "Mukesh Dhanka",
        link: "https://iitgn.ac.in/faculty/bioe/fac-mukesh",
        img: "https://iitgn.ac.in/media/pages/faculty/bioe/fac-mukesh/4095272598-1679554160/mukesh.jpg",
        designation: "Assistant Professor",
        dept: "Biological Engineering",
        email: "mukesh.d@iitgn.ac.in",
        hash: "xPqrgxbd0gZ36blzDpL1",
      },
      {
        name: "Nithin V George",
        link: "https://iitgn.ac.in/faculty/ee/fac-nithin",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-nithin/3164240618-1679554160/nithin.jpg",
        designation: "Associate Professor",
        dept: "Electrical Engineering",
        email: "nithin@iitgn.ac.in",
        hash: "UCLddADFX1VmLmI0c9IJ",
      },
      {
        name: "Yogesh Kumar Meena",
        link: "https://iitgn.ac.in/faculty/cse/yogesh",
        img: "https://iitgn.ac.in/media/pages/faculty/cse/yogesh/2531393478-1684999074/yogesh.webp",
        designation: "Assistant Professor",
        dept: "Computer Science & Engineering",
        email: "yk.meena@iitgn.ac.in",
      },
      {
        name: "Uttama Lahiri",
        link: "https://iitgn.ac.in/faculty/ee/fac-uttama",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-uttama/2986489287-1679554160/uttama.jpg",
        designation: "Professor",
        dept: "Electrical Engineering",
        email: "uttamalahiri@iitgn.ac.in",
      },
      {
        name: "Kaustubh Rane",
        link: "https://iitgn.ac.in/faculty/chemical/fac-kaustubh",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-kaustubh/2144754970-1679554160/kaustubh.JPG",
        designation: "Assistant Professor",
        dept: "Chemical Engineering",
        email: "kaustubhrane@iitgn.ac.in",
      },
      {
        name: "Vineet Vashista",
        link: "https://iitgn.ac.in/faculty/me/15-vineet",
        img: "https://iitgn.ac.in/media/pages/faculty/me/15-vineet/3480943111-1679554160/vineet.JPG",
        designation: "Associate Professor",
        dept: "Mechanical Engineering",
        email: "vineet.vashista@iitgn.ac.in",
      },
      {
        name: "Umashankar Singh",
        link: "https://iitgn.ac.in/faculty/bioe/fac-umashankar",
        img: "https://iitgn.ac.in/media/pages/faculty/bioe/fac-umashankar/1587086601-1679554160/umashankar.jpg",
        designation: "Associate Professor",
        dept: "Biological Engineering",
        email: "usingh@iitgn.ac.in",
        hash: "bwPo3awetYxtStsIR4rr",
      },
      {
        name: "Biswajit Saha",
        link: "https://iitgn.ac.in/faculty/chemical/fac-biswajit",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-biswajit/377347854-1679554160/saha.png",
        designation: "Assistant Professor",
        dept: "Chemical Engineering",
        email: "bsaha@iitgn.ac.in",
      },
      {
        name: "Madhav K Pathak",
        link: "https://iitgn.ac.in/faculty/ee/fac-madhav",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-madhav/739052788-1702634682/madhav.jpg",
        designation: "Assistant Professor",
        dept: "Electrical Engineering",
        email: "madhav.pathak@iitgn.ac.in",
        hash: "MZOfpUYKRYT82Carh9Fa",
      },
      {
        name: "Sudipta Basu",
        link: "https://iitgn.ac.in/faculty/chemistry/fac-sudipta",
        img: "https://iitgn.ac.in/media/pages/faculty/chemistry/fac-sudipta/4089543181-1685686389/sudipta.jpg",
        designation: "Associate Professor",
        dept: "Chemistry",
        email: "sudipta.basu@iitgn.ac.in",
      },
      {
        name: "Superb Misra",
        link: "https://iitgn.ac.in/faculty/mse/fac-superb",
        img: "https://iitgn.ac.in/media/pages/faculty/mse/fac-superb/1833087412-1687604907/superb.jpg",
        designation: "Associate Professor",
        dept: "Materials Engineering",
        email: "smisra@iitgn.ac.in",
      },
      {
        name: "Uddipta Ghosh",
        link: "https://iitgn.ac.in/faculty/me/14-uddipta",
        img: "https://iitgn.ac.in/media/pages/faculty/me/14-uddipta/1170151442-1679554160/uddipta.JPG",
        designation: "Assistant Professor",
        dept: "Mechanical Engineering",
        email: "uddipta.ghosh@iitgn.ac.in",
        hash: "91YpJ4IHRwV5k994icUg",
      },
    ],
  },
  {
    label: "Manufacturing",
    bg: "hover:from-fuchsia-300 hover:to-purple-400",
    card: "from-fuchsia-100 to-purple-200 hover:to-purple-300",
    img: man,
    prof: [
      {
        name: "Iti Gupta",
        link: "https://iitgn.ac.in/faculty/chemistry/fac-iti",
        img: "https://iitgn.ac.in/media/pages/faculty/chemistry/fac-iti/2778770472-1679554159/igupta.JPG",
        designation: "Associate Professor",
        dept: "Chemistry",
        email: "iti@iitgn.ac.in",
        hash: "CdfZUnYNwFobDqnDR8Bn",
      },
      {
        name: "Madhu Vadali",
        link: "https://iitgn.ac.in/faculty/ee/fac-madhu",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-madhu/2464874874-1679554160/madhu.JPG",
        designation: "Assistant Professor",
        dept: "Electrical Engineering (Jointly with Mechanical Engineering)",
        email: "madhu.vadali@iitgn.ac.in",
        hash: "yJhVsNZmSPanaJynyv9D",
      },
      {
        name: "Hari S Ganesh ",
        link: "https://iitgn.ac.in/faculty/chemical/fac-hari",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-hari/3657473632-1685685962/1hari.jpg",
        designation: "Assistant Professor",
        dept: "Chemical Engineering",
        email: "hariganesh@iitgn.ac.in",
        hash: "UX8e5SvLzzpX9EOhctJp",
      },
      {
        name: "Pradipta Ghosh",
        link: "https://iitgn.ac.in/faculty/mse/fac-pradipta",
        img: "https://iitgn.ac.in/media/pages/faculty/mse/fac-pradipta/672297512-1679554159/pradipta.jpg",
        designation: "Assistant Professor",
        dept: "Materials Engineering",
        email: "pradipta.ghosh@iitgn.ac.in",
      },

      {
        name: "Chinmay Ghoroi",
        link: "https://iitgn.ac.in/faculty/chemical/fac-chinmay",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-chinmay/4004635997-1679554160/1chinmay.jpg",
        designation: "Professor",
        dept: "Chemical Engineering",
        email: "chinmayghoroi@gmail.com",
      },
      {
        name: "Superb Misra",
        link: "https://iitgn.ac.in/faculty/mse/fac-superb",
        img: "https://iitgn.ac.in/media/pages/faculty/mse/fac-superb/1833087412-1687604907/superb.jpg",
        designation: "Associate Professor",
        dept: "Materials Engineering",
        email: "smisra@iitgn.ac.in",
      },
      {
        name: "Emila Panda",
        link: "https://iitgn.ac.in/faculty/mse/fac-emila",
        img: "https://iitgn.ac.in/media/pages/faculty/mse/fac-emila/2266883635-1679554159/emila.jpg",
        designation: "Associate Professor",
        dept: "Materials Engineering",
        email: "emila@iitgn.ac.in",
      },
      {
        name: "Ravi Sastri Ayyagari",
        link: "https://iitgn.ac.in/faculty/me/11-ravi",
        img: "https://iitgn.ac.in/media/pages/faculty/me/11-ravi/3905222288-1679554160/rayyagari.JPG",
        designation: "Assistant Professor",
        dept: "Mechanical Engineering",
        email: "ravi.ayyagari@iitgn.ac.in",
      },
      {
        name: "Chandan Kumar",
        link: "https://iitgn.ac.in/faculty/phy/fac-chandan",
        img: "https://iitgn.ac.in/media/pages/faculty/phy/fac-chandan/2381268204-1679554160/chandan.jpg",
        designation: "Assistant Professor",
        dept: "Physics",
        email: "chandan.mishra@iitgn.ac.in",
      },
      {
        name: "Pratyush Dayal",
        link: "https://iitgn.ac.in/faculty/chemical/fac-pratyush",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-pratyush/753090198-1679554160/pratyush.JPG",
        designation: "Associate Professor",
        dept: "Chemical Engineering",
        email: "pdayal@iitgn.ac.in",
      },
      {
        name: "Abhay Raj Singh Gautam",
        link: "https://iitgn.ac.in/faculty/mse/fac-abhay",
        img: "https://iitgn.ac.in/media/pages/faculty/mse/fac-abhay/3742311216-1679554159/abhay.JPG",
        designation: "Associate Professor",
        dept: "Materials Engineering",
        email: "agautam@iitgn.ac.in",
      },
      {
        name: "Jhuma Saha",
        link: "https://iitgn.ac.in/faculty/ee/fac-jhuma",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-jhuma/2070282905-1679554160/jhuma.jpg",
        designation: "Assistant Professor",
        dept: "Electrical Engineering",
        email: "jhuma.saha@iitgn.ac.in",
        hash: "9TF4BN84JqnXPlxvz0O2",
      },
      {
        name: "Nihar Ranjan Mohapatra",
        link: "https://iitgn.ac.in/faculty/ee/fac-nihar",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-nihar/3165356844-1679554160/nihar.jpg",
        designation: "Professor",
        dept: "Electrical Engineering",
        email: "nihar@iitgn.ac.in",
      },
      {
        name: "Sandip Lashkare",
        link: "https://iitgn.ac.in/faculty/ee/fac-sandip",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-sandip/648372802-1692609288/sandip.webp",
        designation: "Assistant Professor",
        dept: "Electrical Engineering",
        email: "sandip.lashkare@iitgn.ac.in",
        hash: "2FxZ4k0GDgAw47klY3S1",
      },
      {
        name: "Prachi Thareja",
        link: "https://iitgn.ac.in/faculty/chemical/fac-prachi",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-prachi/3829953309-1679554160/prachi.jpg",
        designation: "Associate Professor",
        dept: "Chemical Engineering",
        email: "prachi@iitgn.ac.in",
        hash: "WGkLwkHeKdre5O65CYjJ",
      },
      {
        name: "Harini Subramanian",
        link: "https://iitgn.ac.in/faculty/me/6-harini",
        img: "https://iitgn.ac.in/media/pages/faculty/me/6-harini/2617108644-1685361054/harini.webp",
        designation: "Assistant Professor",
        dept: "Mechanical Engineering",
        email: "harini.subramanian@iitgn.ac.in",
        hash: "9dDjyDR8gakvOLlMbTY1",
      },
      {
        name: "Madhav K Pathak",
        link: "https://iitgn.ac.in/faculty/ee/fac-madhav",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-madhav/739052788-1702634682/madhav.jpg",
        designation: "Assistant Professor",
        dept: "Electrical Engineering",
        email: "madhav.pathak@iitgn.ac.in",
        hash: "MZOfpUYKRYT82Carh9Fa",
      },
      {
        name: "Hari S Ganesh",
        link: "https://iitgn.ac.in/faculty/chemical/fac-hari",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-hari/3657473632-1685685962/1hari.jpg",
        designation: "Assistant Professor",
        dept: "Chemical Engineering",
        email: "hariganesh@iitgn.ac.in",
        hash: "UX8e5SvLzzpX9EOhctJp",
      },
    ],
  },
  {
    label: "Energy and Water",
    bg: "hover:from-green-400 hover:to-cyan-300",
    card: "from-green-100 to-cyan-200 hover:to-cyan-300",
    img: ene,
    prof: [
      {
        name: "Chinmay Ghoroi",
        link: "https://iitgn.ac.in/faculty/chemical/fac-chinmay",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-chinmay/4004635997-1679554160/1chinmay.jpg",
        designation: "Professor",
        dept: "Chemical Engineering",
        email: "chinmayghoroi@gmail.com",
      },
      {
        name: "Biswajit Mondal",
        link: "https://iitgn.ac.in/faculty/chemistry/fac-biswajit",
        img: "https://iitgn.ac.in/media/pages/faculty/chemistry/fac-biswajit/4109614119-1679554159/biswajit.jpg",
        designation: "Assistant Professor",
        dept: "Chemistry",
        email: "mondal.biswajit@iitgn.ac.in",
        hash: "N649A3OGb68XX3RfjHTT",
      },
      {
        name: "Rupak Banerjee",
        link: "https://iitgn.ac.in/faculty/phy/fac-rupak",
        img: "https://iitgn.ac.in/media/pages/faculty/phy/fac-rupak/3834261879-1679554160/rupak.jpg",
        designation: "Associate Professor",
        dept: "Physics",
        email: "soumyadipsett@iitgn.ac.in",
        hash: "nBUDFmVilpp7VTpufC0s",
      },
      {
        name: "Atul Bhargav",
        link: "https://iitgn.ac.in/faculty/me/1-atul",
        img: "https://iitgn.ac.in/media/pages/faculty/me/1-atul/160093238-1679554160/atul.JPG",
        designation: "Professor",
        dept: "Mechanical Engineering",
        email: "atul.bhargav@iitgn.ac.in",
      },
      {
        name: "Soumyadip Sett",
        link: "https://iitgn.ac.in/faculty/me/12-soumyadip",
        img: "https://iitgn.ac.in/media/pages/faculty/me/12-soumyadip/19093169-1679554160/1soumyadip.jpg",
        designation: "Assistant Professor",
        dept: "Mechanical Engineering",
        email: "soumyadipsett@iitgn.ac.in",
        hash: "6z0SF1vFgVMVeah9NH08",
      },
      {
        name: "Sriharitha Rowthu",
        link: "https://iitgn.ac.in/faculty/mse/fac-sriharitha",
        img: "https://iitgn.ac.in/media/pages/faculty/mse/fac-sriharitha/3456414939-1679554159/68.png",
        designation: "Assistant Professor",
        dept: "Materials Engineering",
        email: "sriharitha.rowthu@iitgn.ac.in",
      },
      {
        name: "Gopinadhan Kalon",
        link: "https://iitgn.ac.in/faculty/phy/fac-gopinadhan",
        img: "https://iitgn.ac.in/media/pages/faculty/phy/fac-gopinadhan/1792768462-1679554160/gopinadhan.jpg",
        designation: "Associate Professor",
        dept: "Materials Engineering & Physics",
        email: "gopinadhan.kalon@iitgn.ac.in",
        hash: "dHJLg5VbXjtcecUz7I2b",
      },
      {
        name: "Sudhanshu Sharma",
        link: "https://iitgn.ac.in/faculty/chemistry/fac-sudhanshu",
        img: "https://iitgn.ac.in/media/pages/faculty/chemistry/fac-sudhanshu/3921024436-1697179584/sudhanshu.jpg",
        designation: "Associate Professor",
        dept: "Chemistry",
        email: "ssharma@iitgn.ac.in",
      },
      {
        name: "Naran M Pindoriya",
        link: "https://iitgn.ac.in/faculty/ee/fac-naran",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-naran/2673304336-1679554160/naran.JPG",
        designation: "Associate Professor",
        dept: "Electrical Engineering",
        email: "naran@iitgn.ac.in",
      },
      {
        name: "Saumyakanti Khatua",
        link: "https://iitgn.ac.in/faculty/chemistry/fac-saumyakanti",
        img: "https://iitgn.ac.in/media/pages/faculty/chemistry/fac-saumyakanti/163641175-1679554159/saumyakanti.JPG",
        designation: "Associate Professor",
        dept: "Chemistry",
        email: "khatuask@iitgn.ac.in",
      },
      {
        name: "Pallavi Bharadwaj",
        link: "https://iitgn.ac.in/faculty/ee/fac-pallavi",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-pallavi/838604894-1679554160/pallavi-2.jpg",
        designation: "Assistant Professor",
        dept: "Electrical Engineering",
        email: "pallavib@iitgn.ac.in",
        hash: "sNrgEwvEyy4rNyZ1RhE1",
      },
      {
        name: "Ragavan K",
        link: "https://iitgn.ac.in/faculty/ee/fac-ragavan",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-ragavan/3529429094-1679554160/ragavan.JPG",
        designation: "Associate Professor",
        dept: "Electrical Engineering",
        email: "ragavan@iitgn.ac.in",
        hash: "WeAySORJuOmnKgR0FDcJ",
      },
      {
        name: "Pankaj Khanna",
        link: "https://iitgn.ac.in/faculty/earths/fac-pankaj",
        img: "https://iitgn.ac.in/media/pages/faculty/earths/fac-pankaj/1088819592-1679554159/khanna.png",
        designation: "Assistant Professor",
        dept: "Earth Sciences",
        email: "pankaj.khanna@iitgn.ac.in",
        hash: "rgqCfstJpP19c71ruHfr",
      },
      {
        name: "Kaustubh Rane",
        link: "https://iitgn.ac.in/faculty/chemical/fac-kaustubh",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-kaustubh/2144754970-1679554160/kaustubh.JPG",
        designation: "Associate Professor",
        dept: "Chemical Engineering",
        email: "kaustubhrane@iitgn.ac.in",
      },
      {
        name: "Abinaya Sampat",
        link: "https://iitgn.ac.in/faculty/chemical/fac-abinaya",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-abinaya/1754432438-1679554160/abhinya.png",
        designation: "Assistant Professor",
        dept: "Chemical Engineering",
        email: "abinaya.sampath@iitgn.ac.in",
        hash: "Ig5Wlgtp0X7ixMoL47ym",
      },
      {
        name: "Anirban Mondal",
        link: "https://iitgn.ac.in/faculty/chemistry/fac-anirban",
        img: "https://iitgn.ac.in/media/pages/faculty/chemistry/fac-anirban/2584301664-1685686297/AnirbanMondalIITGN2.jpg",
        designation: "Assistant Professor",
        dept: "Chemistry",
        email: "amondal@iitgn.ac.in",
        hash: "jdCC4IhzoAjB62WQXUyU",
      },
      {
        name: "Biswajit Saha",
        link: "https://iitgn.ac.in/faculty/chemical/fac-biswajit",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-biswajit/377347854-1679554160/saha.png",
        designation: "Assistant Professor",
        dept: "Chemical Engineering",
        email: "bsaha@iitgn.ac.in",
      },
      {
        name: "Manish Kumar",
        link: "https://iitgn.ac.in/faculty/civil/fac-manish",
        img: "https://iitgn.ac.in/media/pages/faculty/civil/fac-manish/1661862319-1701344470/1manish2023.jpg",
        designation: "Associate Professor",
        dept: "Civil Engineering",
        email: "mkumar@iitgn.ac.in",
        hash: "mP9fxA0xDhp2htPl8ehW",
      },
      {
        name: "Iti Gupta",
        link: "https://iitgn.ac.in/faculty/chemistry/fac-iti",
        img: "https://iitgn.ac.in/media/pages/faculty/chemistry/fac-iti/2778770472-1679554159/igupta.JPG",
        designation: "Associate Professor",
        dept: "Chemistry",
        email: "iti@iitgn.ac.in",
        hash: "CdfZUnYNwFobDqnDR8Bn",
      },
      {
        name: "Utsav Mannu",
        link: "https://iitgn.ac.in/faculty/earths/fac-utsav",
        img: "https://iitgn.ac.in/media/pages/faculty/earths/fac-utsav/956763846-1679554159/utsav.jpeg",
        designation: "Assistant Professor",
        dept: "Earth Sciences",
        email: "utsav.mannu@iitgn.ac.in",
      },
      {
        name: "Hari S Ganesh",
        link: "https://iitgn.ac.in/faculty/chemical/fac-hari",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-hari/3657473632-1685685962/1hari.jpg",
        designation: "Assistant Professor",
        dept: "Chemical Engineering",
        email: "hariganesh@iitgn.ac.in",
        hash: "UX8e5SvLzzpX9EOhctJp",
      },
      {
        name: "Superb Misra",
        link: "https://iitgn.ac.in/faculty/mse/fac-superb",
        img: "https://iitgn.ac.in/media/pages/faculty/mse/fac-superb/1833087412-1687604907/superb.jpg",
        designation: "Associate Professor",
        dept: "Materials Engineering",
        email: "smisra@iitgn.ac.in",
      },
      {
        name: "Uddipta Ghosh",
        link: "https://iitgn.ac.in/faculty/me/14-uddipta",
        img: "https://iitgn.ac.in/media/pages/faculty/me/14-uddipta/1170151442-1679554160/uddipta.JPG",
        designation: "Assistant Professor",
        dept: "Mechanical Engineering",
        email: "uddipta.ghosh@iitgn.ac.in",
        hash: "91YpJ4IHRwV5k994icUg",
      },
      {
        name: "Bhaskar Datta",
        link: "https://iitgn.ac.in/faculty/bioe/fac-bhaskar",
        img: "https://iitgn.ac.in/media/pages/faculty/bioe/fac-bhaskar/1847654198-1679554160/bhaskar.JPG",
        designation: "Associate Professor",
        dept: "Biological Sciences and Engineering (Jointly with Chemistry)",
        email: "bdatta@iitgn.ac.in",
      },
    ],
  },
  {
    label: "AI and Computing",
    bg: "hover:from-purple-300 hover:to-indigo-300",
    card: "from-purple-100 to-indigo-200 hover:to-indigo-300",
    img: ai,
    prof: [
      {
        name: "Raghavan Ranganathan",
        link: "https://iitgn.ac.in/faculty/mse/fac-raghavan",
        img: "https://iitgn.ac.in/media/pages/faculty/mse/fac-raghavan/3479334007-1679554159/ranganathan.JPG",
        designation: "Assistant Professor",
        dept: "Materials Engineering",
        email: "rraghav@iitgn.ac.in",
      },
      {
        name: "Shanmuganathan Raman",
        link: "https://iitgn.ac.in/faculty/cse/shanmuganathan",
        img: "https://iitgn.ac.in/media/pages/faculty/cse/shanmuganathan/1523958848-1679554159/1_shanmuganathan.jpg",
        designation: "Associate Professor",
        dept: "Computer Science & Engineering (Jointly with Electrical Engineering)",
        email: "shanmuga@iitgn.ac.in",
      },
      {
        name: "Mayank Singh",
        link: "https://iitgn.ac.in/faculty/cse/mayank",
        img: "https://iitgn.ac.in/media/pages/faculty/cse/mayank/923634747-1679554159/mayank.jpg",
        designation: "Assistant Professor",
        dept: "Computer Science & Engineering",
        email: "singh.mayank@iitgn.ac.in",
      },
      {
        name: "Yogesh Kumar Meena",
        link: "https://iitgn.ac.in/faculty/cogs/fac-yogesh",
        img: "https://iitgn.ac.in/media/pages/faculty/cogs/fac-yogesh/2531393478-1707370226/yogesh.webp",
        designation: "Assistant Professor",
        dept: "Computer Science & Engineering",
        email: "yk.meena@iitgn.ac.in",
      },
      {
        name: "Kaustubh Rane",
        link: "https://iitgn.ac.in/faculty/chemical/fac-kaustubh",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-kaustubh/2144754970-1679554160/kaustubh.JPG",
        designation: "Assistant Professor",
        dept: "Chemical Engineering",
        email: "kaustubhrane@iitgn.ac.in",
      },
      {
        name: "Rajat Moona",
        link: "https://iitgn.ac.in/faculty/cse/rajat-moona",
        img: "https://iitgn.ac.in/media/pages/faculty/cse/rajat-moona/2905206850-1679554159/rajat-moona.jpg",
        designation: "Professor",
        dept: "Computer Science & Engineering",
        email: "ashutosh.s@iitgn.ac.in",
      },
      {
        name: "Anirban Mondal",
        link: "https://iitgn.ac.in/faculty/chemistry/fac-anirban",
        img: "https://iitgn.ac.in/media/pages/faculty/chemistry/fac-anirban/2584301664-1685686297/AnirbanMondalIITGN2.jpg",
        designation: "Assistant Professor",
        dept: "Chemistry",
        email: "amondal@iitgn.ac.in",
        hash: "jdCC4IhzoAjB62WQXUyU",
      },
      {
        name: "Neeldhara Misra",
        link: "https://iitgn.ac.in/faculty/cse/neeldhara",
        img: "https://iitgn.ac.in/media/pages/faculty/cse/neeldhara/2444387690-1679554159/neeldhara1.jpg",
        designation: "Associate Professor",
        dept: "Computer Science & Engineering",
        email: "neeldhara.m@iitgn.ac.in",
      },
      {
        name: "Anirban Dasgupta",
        link: "https://iitgn.ac.in/faculty/cse/anirban",
        img: "https://iitgn.ac.in/media/pages/faculty/cse/anirban/729890348-1679554159/anirban.jpg",
        designation: "Professor",
        dept: "Computer Science & Engineering",
        email: "anirbandg@iitgn.ac.in",
      },
      {
        name: "Nipun Batra",
        link: "https://iitgn.ac.in/faculty/cse/nipun",
        img: "https://iitgn.ac.in/media/pages/faculty/cse/nipun/3587009419-1679554159/nipun.jpg",
        designation: "Assistant Professor",
        dept: "Computer Science & Engineering",
        email: "nipun.batra@iitgn.ac.in",
        hash: "3bfPAe8GjWbOPuh47uCk",
      },
      {
        name: "Manoj Gupta",
        link: "https://iitgn.ac.in/faculty/cse/manoj",
        img: "https://iitgn.ac.in/media/pages/faculty/cse/manoj/3375263455-1679554159/manoj.JPG",
        designation: "Assistant Professor",
        dept: "Computer Science & Engineering",
        email: "gmanoj@iitgn.ac.in",
      },
      {
        name: "Krishna Prasad Miyapuram",
        link: "https://iitgn.ac.in/faculty/hss/fac-krishna",
        img: "https://iitgn.ac.in/media/pages/faculty/hss/fac-krishna/4016078106-1679554159/krishna.jpg",
        designation: "Associate Professor",
        dept: "Cognitive and Brain Sciences",
        email: "kprasad@iitgn.ac.in",
      },
      {
        name: "Uttama Lahiri",
        link: "https://iitgn.ac.in/faculty/ee/fac-uttama",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-uttama/2986489287-1679554160/uttama.jpg",
        designation: "Professor",
        dept: "Electrical Engineering",
        email: "uttamalahiri@iitgn.ac.in",
      },
      {
        name: "Sushobhan Sen",
        link: "https://iitgn.ac.in/faculty/civil/fac-sushobhan",
        img: "https://iitgn.ac.in/media/pages/faculty/civil/fac-sushobhan/1627401271-1679554160/sushobhan.png",
        designation: "Assistant Professor",
        dept: "Civil Engineering",
        email: "sushobhan.sen@iitgn.ac.in",
        hash: "459ms5qYkX92oWXvlPFk",
      },
      {
        name: "Abhishek Bhicchawat",
        link: "https://iitgn.ac.in/faculty/cse/abhishek",
        img: "https://iitgn.ac.in/media/pages/faculty/cse/abhishek/962353777-1679554159/avhishek.jpg",
        designation: "Assistant Professor",
        dept: "Computer Science & Engineering",
        email: "abhishek.b@iitgn.ac.in",
      },
      {
        name: "Sandip Lashkare",
        link: "https://iitgn.ac.in/faculty/ee/fac-sandip",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-sandip/648372802-1692609288/sandip.webp",
        designation: "Assistant Professor",
        dept: "Electrical Engineering",
        email: "sandip.lashkare@iitgn.ac.in",
        hash: "2FxZ4k0GDgAw47klY3S1",
      },
      {
        name: "Pallavi Bharadwaj",
        link: "https://iitgn.ac.in/faculty/ee/fac-pallavi",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-pallavi/838604894-1679554160/pallavi-2.jpg",
        designation: "Assistant Professor",
        dept: "Electrical Engineering",
        email: "pallavib@iitgn.ac.in",
        hash: "sNrgEwvEyy4rNyZ1RhE1",
      },
      {
        name: "Shouvick Mondal",
        link: "https://iitgn.ac.in/faculty/cse/shouvick",
        img: "https://iitgn.ac.in/media/pages/faculty/cse/shouvick/1816765913-1685686569/shouvik2.jpg",
        designation: "Assistant Professor",
        dept: "Computer Science & Engineering",
        email: "sandip.lashkare@iitgn.ac.in",
        hash: "tx2VDMcq4PSYhMw1a0pj",
      },
      {
        name: "Biswajit Saha",
        link: "https://iitgn.ac.in/faculty/chemical/fac-biswajit",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-biswajit/377347854-1679554160/saha.png",
        designation: "Assistant Professor",
        dept: "Chemical Engineering",
        email: "bsaha@iitgn.ac.in",
      },
      {
        name: "Harish Palanthandalam-Madapusi",
        link: "https://iitgn.ac.in/faculty/me/6-harish",
        img: "https://iitgn.ac.in/media/pages/faculty/me/6-harish/1195998939-1679554160/harish.jpg",
        designation: "Associate Professor",
        dept: "Mechanical Engineering",
        email: "harish@iitgn.ac.in",
      },
      {
        name: "Anand Sengupta",
        link: "https://iitgn.ac.in/faculty/phy/fac-anand",
        img: "https://iitgn.ac.in/media/pages/faculty/phy/fac-anand/1948160586-1679554160/anand.JPG",
        designation: "Associate Professor",
        dept: "Physics",
        email: "asengupta@iitgn.ac.in",
        hash: "Q3CyEgrbdEIfi52otORh",
      },
      {
        name: "Madhav K Pathak",
        link: "https://iitgn.ac.in/faculty/ee/fac-madhav",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-madhav/739052788-1702634682/madhav.jpg",
        designation: "Assistant Professor",
        dept: "Electrical Engineering",
        email: "madhav.pathak@iitgn.ac.in",
        hash: "MZOfpUYKRYT82Carh9Fa",
      },
      {
        name: "B. Prasanna Venkatesh",
        link: "https://iitgn.ac.in/faculty/phy/fac-prasanna",
        img: "https://iitgn.ac.in/media/pages/faculty/phy/fac-prasanna/2801434699-1679554160/prasanna.jpg",
        designation: "Assistant Professor",
        dept: "Physics",
        email: "prasanna.b@iitgn.ac.in",
        hash: "ulbex5zXkQ39halP9HcI",
      },
    ],
  },
  {
    label: "Agro and Food processing",
    bg: "hover:from-yellow-400 hover:to-orange-300",
    card: "from-yellow-100 to-orange-200 hover:to-orange-300",
    img: food,
    prof: [
      {
        name: "Soumyadip Sett",
        link: "https://iitgn.ac.in/faculty/me/12-soumyadip",
        img: "https://iitgn.ac.in/media/pages/faculty/me/12-soumyadip/19093169-1679554160/1soumyadip.jpg",
        designation: "Assistant Professor",
        dept: "Mechanical Engineering",
        email: "soumyadipsett@iitgn.ac.in",
        hash: "6z0SF1vFgVMVeah9NH08",
      },
      {
        name: "Subramanian Sankaranarayanan",
        link: "https://iitgn.ac.in/faculty/bioe/fac-subramanian",
        img: "https://iitgn.ac.in/media/pages/faculty/bioe/fac-subramanian/3118450367-1679554160/Subramanian.jpg",
        designation: "Assistant Professor",
        dept: "Biological Sciences and Engineering",
        email: "s.sankar@iitgn.ac.in",
        hash: "UbJ1Co3vQrSaHBwQJKOZ",
      },
      {
        name: "Bhaskar Datta",
        link: "https://iitgn.ac.in/faculty/bioe/fac-bhaskar",
        img: "https://iitgn.ac.in/media/pages/faculty/bioe/fac-bhaskar/1847654198-1679554160/bhaskar.JPG",
        designation: "Associate Professor",
        dept: "Biological Sciences and Engineering (Jointly with Chemistry)",
        email: "bdatta@iitgn.ac.in",
      },
      {
        name: "Prachi Thareja",
        link: "https://iitgn.ac.in/faculty/chemical/fac-prachi",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-prachi/3829953309-1679554160/prachi.jpg",
        designation: "Associate Professor",
        dept: "Chemical Engineering",
        email: "prachi@iitgn.ac.in",
        hash: "WGkLwkHeKdre5O65CYjJ",
      },
      {
        name: "Vineet Vashista ",
        link: "https://iitgn.ac.in/faculty/me/15-vineet",
        img: "https://iitgn.ac.in/media/pages/faculty/me/15-vineet/3480943111-1679554160/vineet.JPG",
        designation: "Associate Professor",
        dept: "Mechanical Engineering",
        email: "vineet.vashista@iitgn.ac.in",
      },
      {
        name: "Biswajit Saha",
        link: "https://iitgn.ac.in/faculty/chemical/fac-biswajit",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-biswajit/377347854-1679554160/saha.png",
        designation: "Assistant Professor",
        dept: "Chemical Engineering",
        email: "bsaha@iitgn.ac.in",
      },
    ],
  },
  {
    label: "Defence, Military & Space Technology ",
    bg: "hover:from-pink-300 hover:to-rose-300",
    card: "from-pink-100 to-rose-200 hover:to-rose-300",
    img: def,
    prof: [
      {
        name: "Raghavan Ranganathan",
        link: "https://iitgn.ac.in/faculty/mse/fac-raghavan",
        img: "https://iitgn.ac.in/media/pages/faculty/mse/fac-raghavan/3479334007-1679554159/ranganathan.JPG",
        designation: "Assistant Professor",
        dept: "Materials Engineering",
        email: "rraghav@iitgn.ac.in",
      },
      {
        name: "Biswajit Saha ",
        link: "https://iitgn.ac.in/faculty/chemical/fac-biswajit",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-biswajit/377347854-1679554160/saha.png",
        designation: "Assistant Professor",
        dept: "Chemical Engineering",
        email: "bsaha@iitgn.ac.in",
      },
      {
        name: "Kabeer Jasuja",
        link: "https://iitgn.ac.in/faculty/chemical/fac-kabeer",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-kabeer/2456190777-1685969243/kabeer.webp",
        designation: "Associate Professor",
        dept: "Chemical Engineering",
        email: "kabeer@iitgn.ac.in",
      },
      {
        name: "Vineet Vashista ",
        link: "https://iitgn.ac.in/faculty/me/15-vineet",
        img: "https://iitgn.ac.in/media/pages/faculty/me/15-vineet/3480943111-1679554160/vineet.JPG",
        designation: "Associate Professor",
        dept: "Mechanical Engineering",
        email: "vineet.vashista@iitgn.ac.in",
      },
      {
        name: "Harish P M",
        link: "https://iitgn.ac.in/faculty/me/6-harish",
        img: "https://iitgn.ac.in/media/pages/faculty/me/6-harish/1195998939-1679554160/harish.jpg",
        designation: "Associate Professor",
        dept: "Mechanical Engineering",
        email: "harish@iitgn.ac.in",
      },
      {
        name: "Arup Lal Chakraborty",
        link: "https://iitgn.ac.in/faculty/ee/fac-arup",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-arup/3817653843-1679554160/1arup.jpg",
        designation: "Professor",
        dept: "Electrical Engineering",
        email: "arup@iitgn.ac.in",
      },
      {
        name: "Manish Kumar",
        link: "https://iitgn.ac.in/faculty/civil/fac-manish",
        img: "https://iitgn.ac.in/media/pages/faculty/civil/fac-manish/1661862319-1701344470/1manish2023.jpg",
        designation: "Associate Professor",
        dept: "Civil Engineering",
        email: "mkumar@iitgn.ac.in",
        hash: "mP9fxA0xDhp2htPl8ehW",
      },
      {
        name: "Nithin George",
        link: "https://iitgn.ac.in/faculty/ee/fac-nithin",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-nithin/3164240618-1679554160/nithin.jpg",
        designation: "Associate Professor",
        dept: "Electrical Engineering",
        email: "nithin@iitgn.ac.in",
      },
      {
        name: "Pallavi Bharadwaj",
        link: "https://iitgn.ac.in/faculty/ee/fac-pallavi",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-pallavi/838604894-1679554160/pallavi-2.jpg",
        designation: "Assistant Professor",
        dept: "Electrical Engineering",
        email: "pallavib@iitgn.ac.in",
        hash: "sNrgEwvEyy4rNyZ1RhE1",
      },
      {
        name: "Krista R Khiangte",
        link: "https://iitgn.ac.in/faculty/phy/fac-krista",
        img: "https://iitgn.ac.in/media/pages/faculty/phy/fac-krista/245964321-1679554160/krista.png",
        designation: "Assistant Professor",
        dept: "Physics",
        email: "dilip.sundaram@iitgn.ac.in",
        hash: "NfX5HfusHIwdPtStkIvj",
      },
      {
        name: "Jhuma Saha",
        link: "https://iitgn.ac.in/faculty/ee/fac-jhuma",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-jhuma/2070282905-1679554160/jhuma.jpg",
        designation: "Assistant Professor",
        dept: "Electrical Engineering",
        email: "jhuma.saha@iitgn.ac.in",
        hash: "9TF4BN84JqnXPlxvz0O2",
      },
      {
        name: "Shouvick Mondal",
        link: "https://iitgn.ac.in/faculty/cse/shouvick",
        img: "https://iitgn.ac.in/media/pages/faculty/cse/shouvick/1816765913-1685686569/shouvik2.jpg",
        designation: "Assistant Professor",
        dept: "Computer Science & Engineering",
        email: "sandip.lashkare@iitgn.ac.in",
      },
      {
        name: "Soumyabrata Chakrabarty",
        link: "https://iitgn.ac.in/faculty/ee/fac-sbchakrabarty",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-sbchakrabarty/2694341018-1679554160/sbchakrabarty.JPG",
        designation: "Visiting Professor",
        dept: "Electrical Engineering",
        email: "soumyabrata.c@iitgn.ac.in",
        hash: "tjo13tvVFlLljjBKv02H",
      },
      {
        name: "Harini Subramanian",
        link: "https://iitgn.ac.in/faculty/me/6-harini",
        img: "https://iitgn.ac.in/media/pages/faculty/me/6-harini/2617108644-1685361054/harini.webp",
        designation: "Assistant Professor",
        dept: "Mechanical Engineering",
        email: "harini.subramanian@iitgn.ac.in",
        hash: "9dDjyDR8gakvOLlMbTY1",
      },
      {
        name: "Madhav K Pathak",
        link: "https://iitgn.ac.in/faculty/ee/fac-madhav",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-madhav/739052788-1702634682/madhav.jpg",
        designation: "Assistant Professor",
        dept: "Electrical Engineering",
        email: "madhav.pathak@iitgn.ac.in",
        hash: "MZOfpUYKRYT82Carh9Fa",
      },
      {
        name: "Vinod Narayanan",
        link: "https://iitgn.ac.in/faculty/me/16-vinod",
        img: "https://iitgn.ac.in/media/pages/faculty/me/16-vinod/2339248039-1679554160/vinod.JPG",
        designation: "Associate Professor",
        dept: "Mechanical Engineering",
        email: "vinod@iitgn.ac.in",
        hash: "QOFMKrB6HMkySYvAp522",
      },
    ],
  },
  {
    label: "Climate Challenge & Solutions",
    bg: "hover:from-blue-400 hover:to-indigo-300",
    card: "from-blue-100 to-indigo-200 hover:to-indigo-300",
    img: climate,
    prof: [
      {
        name: "Ambika Aiyadurai",
        link: "https://iitgn.ac.in/faculty/hss/fac-ambika",
        img: "https://iitgn.ac.in/media/pages/faculty/hss/fac-ambika/3276174761-1679554159/ambika.jpg",
        designation: "Associate Professor",
        dept: "Humanities and Social Sciences",
        email: "a.ambika@iitgn.ac.in",
        hash: "2mfqHa0RYB67QZfVKvaj",
      },
      {
        name: "Sharada Channarayapatna",
        link: "https://iitgn.ac.in/faculty/hss/fac-sharada",
        img: "https://iitgn.ac.in/media/pages/faculty/hss/fac-sharada/3181150697-1679554159/Sharada-new.jpg",
        designation: "Assistant Professor",
        dept: "Earth Sciences & Humanities and Social Sciences",
        email: "sharada.c@iitgn.ac.in",
        hash: "Hm9gEcUNLEt9GQ4XoFJX",
      },
      {
        name: "Vimal Mishra",
        link: "https://iitgn.ac.in/faculty/earths/fac-vimal",
        img: "https://iitgn.ac.in/media/pages/faculty/earths/fac-vimal/643523841-1704108752/vimal.jpg",
        designation: "Professor",
        dept: "Civil Engineering and Earth Sciences",
        email: "vmishra@iitgn.ac.in",
      },
      {
        name: "Pankaj Khanna",
        link: "https://iitgn.ac.in/faculty/earths/fac-pankaj",
        img: "https://iitgn.ac.in/media/pages/faculty/earths/fac-pankaj/1088819592-1679554159/khanna.png",
        designation: "Assistant Professor",
        dept: "Earth Sciences",
        email: "pankaj.khanna@iitgn.ac.in",
      },
      {
        name: "Udit Bhatia",
        link: "https://iitgn.ac.in/faculty/civil/fac-udit",
        img: "https://iitgn.ac.in/media/pages/faculty/civil/fac-udit/2308710421-1679554160/0udit.jpg",
        designation: "Assistant Professor",
        dept: "Civil Engineering",
        email: "bhatia.u@iitgn.ac.in",
      },
      {
        name: "Vikrant Jain",
        link: "https://iitgn.ac.in/faculty/earths/fac-vikrant",
        img: "https://iitgn.ac.in/media/pages/faculty/earths/fac-vikrant/472889722-1679554159/vikrant.JPG",
        designation: "Professor",
        dept: "Earth Sciences",
        email: "vjain@iitgn.ac.in",
      },
      {
        name: "Gopinadhan Kalon",
        link: "https://iitgn.ac.in/faculty/phy/fac-gopinadhan",
        img: "https://iitgn.ac.in/media/pages/faculty/phy/fac-gopinadhan/1792768462-1679554160/gopinadhan.jpg",
        designation: "Associate Professor",
        dept: "Materials Engineering & Physics",
        email: "gopinadhan.kalon@iitgn.ac.in",
        hash: "dHJLg5VbXjtcecUz7I2b",
      },
      {
        name: "Abinaya Sampat",
        link: "https://iitgn.ac.in/faculty/chemical/fac-abinaya",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-abinaya/1754432438-1679554160/abhinya.png",
        designation: "Assistant Professor",
        dept: "Chemical Engineering",
        email: "abinaya.sampath@iitgn.ac.in",
        hash: "Ig5Wlgtp0X7ixMoL47ym",
      },
      {
        name: "Ashutosh Srivastava",
        link: "https://iitgn.ac.in/faculty/bioe/fac-ashutosh",
        img: "https://iitgn.ac.in/media/pages/faculty/bioe/fac-ashutosh/1199779951-1685685814/Ashutosh.jpg",
        designation: "Assistant Professor",
        dept: "Biological Sciences and Engineering",
        email: "ashutosh.s@iitgn.ac.in",
        hash: "66pRjErPQgxIrHmDK6BD",
      },
      {
        name: "Pallavi Bharadwaj",
        link: "https://iitgn.ac.in/faculty/ee/fac-pallavi",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-pallavi/838604894-1679554160/pallavi-2.jpg",
        designation: "Assistant Professor",
        dept: "Electrical Engineering",
        email: "pallavib@iitgn.ac.in",
        hash: "sNrgEwvEyy4rNyZ1RhE1",
      },
      {
        name: "Soumyadip Sett",
        link: "https://iitgn.ac.in/faculty/me/12-soumyadip",
        img: "https://iitgn.ac.in/media/pages/faculty/me/12-soumyadip/19093169-1679554160/1soumyadip.jpg",
        designation: "Assistant Professor",
        dept: "Mechanical Engineering",
        email: "soumyadipsett@iitgn.ac.in",
        hash: "6z0SF1vFgVMVeah9NH08",
      },
      {
        name: "Anirban Mondal",
        link: "https://iitgn.ac.in/faculty/chemistry/fac-anirban",
        img: "https://iitgn.ac.in/media/pages/faculty/chemistry/fac-anirban/2584301664-1685686297/AnirbanMondalIITGN2.jpg",
        designation: "Assistant Professor",
        dept: "Chemistry",
        email: "amondal@iitgn.ac.in",
        hash: "jdCC4IhzoAjB62WQXUyU",
      },
      {
        name: "Manish Kumar",
        link: "https://iitgn.ac.in/faculty/civil/fac-manish",
        img: "https://iitgn.ac.in/media/pages/faculty/civil/fac-manish/1661862319-1701344470/1manish2023.jpg",
        designation: "Associate Professor",
        dept: "Civil Engineering",
        email: "mkumar@iitgn.ac.in",
        hash: "mP9fxA0xDhp2htPl8ehW",
      },
      {
        name: "Arup Lal Chakraborty",
        link: "https://iitgn.ac.in/faculty/ee/fac-arup",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-arup/3817653843-1679554160/1arup.jpg",
        designation: "Professor",
        dept: "Electrical Engineering",
        email: "arup@iitgn.ac.in",
      },
      {
        name: "Sushobhan Sen",
        link: "https://iitgn.ac.in/faculty/civil/fac-sushobhan",
        img: "https://iitgn.ac.in/media/pages/faculty/civil/fac-sushobhan/1627401271-1679554160/sushobhan.png",
        designation: "Assistant Professor",
        dept: "Civil Engineering",
        email: "sushobhan.sen@iitgn.ac.in",
        hash: "459ms5qYkX92oWXvlPFk",
      },
      {
        name: "Madhav K Pathak",
        link: "https://iitgn.ac.in/faculty/ee/fac-madhav",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-madhav/739052788-1702634682/madhav.jpg",
        designation: "Assistant Professor",
        dept: "Electrical Engineering",
        email: "madhav.pathak@iitgn.ac.in",
        hash: "MZOfpUYKRYT82Carh9Fa",
      },
      {
        name: "Priyabrata Ghana",
        link: "https://iitgn.ac.in/faculty/chemistry/fac-priyabrata",
        img: "https://iitgn.ac.in/media/pages/faculty/chemistry/fac-priyabrata/2193768978-1685080484/priyabatra.jpg",
        designation: "Assistant Professor",
        dept: "Chemistry",
        email: "priyabrata.ghana@iitgn.ac.in",
        hash: "1r8kXtbPsP3bxOxNCXZX",
      },
      {
        name: "Bhaskar Datta",
        link: "https://iitgn.ac.in/faculty/bioe/fac-bhaskar",
        img: "https://iitgn.ac.in/media/pages/faculty/bioe/fac-bhaskar/1847654198-1679554160/bhaskar.JPG",
        designation: "Associate Professor",
        dept: "Biological Sciences and Engineering (Jointly with Chemistry)",
        email: "bdatta@iitgn.ac.in",
      },
    ],
  },
  {
    label: "Infrastructure",
    bg: "hover:from-blue-400 hover:to-indigo-300",
    card: "from-blue-100 to-indigo-200 hover:to-indigo-300",
    img: infra,
    prof: [
      {
        name: "Vimal Mishra",
        link: "https://iitgn.ac.in/faculty/earths/fac-vimal",
        img: "https://iitgn.ac.in/media/pages/faculty/earths/fac-vimal/643523841-1704108752/vimal.jpg",
        designation: "Professor",
        dept: "Civil Engineering and Earth Sciences",
        email: "vmishra@iitgn.ac.in",
      },
      {
        name: "Ajanta Sachan",
        link: "https://iitgn.ac.in/hi/faculty/civil/fac-ajanta",
        img: "https://iitgn.ac.in/media/pages/faculty/civil/fac-ajanta/3682568250-1679554160/ajanta.png",
        designation: "Associate Professor",
        dept: "Civil Engineering",
        email: "ajanta@iitgn.ac.in",
        hash: "qSkdA5ofoJ3bRsqLdGQ3",
      },
      {
        name: "Udit Bhatia",
        link: "https://iitgn.ac.in/faculty/civil/fac-udit",
        img: "https://iitgn.ac.in/media/pages/faculty/civil/fac-udit/2308710421-1679554160/0udit.jpg",
        designation: "Assistant Professor",
        dept: "Civil Engineering",
        email: "bhatia.u@iitgn.ac.in",
      },
      {
        name: "Gaurav Srivastava",
        link: "https://iitgn.ac.in/faculty/civil/fac-gaurav",
        img: "https://iitgn.ac.in/media/pages/faculty/civil/fac-gaurav/2853377267-1685686496/gaurav2.jpg",
        designation: "Professor",
        dept: "Civil Engineering",
        email: "gauravs@iitgn.ac.in",
      },
      {
        name: "Amit Prashant",
        link: "https://iitgn.ac.in/faculty/civil/fac-amit",
        img: "https://iitgn.ac.in/media/pages/faculty/civil/fac-amit/1240420610-1679554160/amit.jpg",
        designation: "Professor",
        dept: "Civil Engineering",
        email: "ap@iitgn.ac.in",
      },
      {
        name: "Manish Kumar",
        link: "https://iitgn.ac.in/faculty/civil/fac-manish",
        img: "https://iitgn.ac.in/media/pages/faculty/civil/fac-manish/1661862319-1701344470/1manish2023.jpg",
        designation: "Associate Professor",
        dept: "Civil Engineering",
        email: "mkumar@iitgn.ac.in",
        hash: "mP9fxA0xDhp2htPl8ehW",
      },
      {
        name: "Sushobhan Sen",
        link: "https://iitgn.ac.in/faculty/civil/fac-sushobhan",
        img: "https://iitgn.ac.in/media/pages/faculty/civil/fac-sushobhan/1627401271-1679554160/sushobhan.png",
        designation: "Assistant Professor",
        dept: "Civil Engineering",
        email: "sushobhan.sen@iitgn.ac.in",
        hash: "459ms5qYkX92oWXvlPFk",
      },
      {
        name: "Utsav Mannu",
        link: "https://iitgn.ac.in/faculty/earths/fac-utsav",
        img: "https://iitgn.ac.in/media/pages/faculty/earths/fac-utsav/956763846-1679554159/utsav.jpeg",
        designation: "Assistant Professor",
        dept: "Civil Engineering",
        email: "utsav.mannu@iitgn.ac.in",
      },
    ],
  },
  {
    label: "Healthcare and Pharmaceuticals",
    bg: "hover:from-cyan-400  hover:to-blue-500",
    card: "from-cyan-100  to-blue-200 hover:to-blue-300",
    img: pharma,
    prof: [
      {
        name: "Raghavan Ranganathan",
        link: "https://iitgn.ac.in/faculty/mse/fac-raghavan",
        img: "https://iitgn.ac.in/media/pages/faculty/mse/fac-raghavan/3479334007-1679554159/ranganathan.JPG",
        designation: "Assistant Professor",
        dept: "Materials Engineering",
        email: "rraghav@iitgn.ac.in",
      },
      {
        name: "Chinmay Ghoroi",
        link: "https://iitgn.ac.in/faculty/chemical/fac-chinmay",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-chinmay/4004635997-1679554160/1chinmay.jpg",
        designation: "Professor",
        dept: "Chemical Engineering",
        email: "chinmayghoroi@gmail.com",
      },
      {
        name: "Uttama Lahiri",
        link: "https://iitgn.ac.in/faculty/ee/fac-uttama",
        img: "https://iitgn.ac.in/media/pages/faculty/ee/fac-uttama/2986489287-1679554160/uttama.jpg",
        designation: "Professor",
        dept: "Electrical Engineering",
        email: "uttamalahiri@iitgn.ac.in",
      },
      {
        name: "Iti Gupta",
        link: "https://iitgn.ac.in/faculty/chemistry/fac-iti",
        img: "https://iitgn.ac.in/media/pages/faculty/chemistry/fac-iti/2778770472-1679554159/igupta.JPG",
        designation: "Associate Professor",
        dept: "Chemistry",
        email: "uttamalahiri@iitgn.ac.in",
        hash: "CdfZUnYNwFobDqnDR8Bn",
      },
      {
        name: "Chandrakumar Appayee",
        link: "https://iitgn.ac.in/faculty/chemistry/fac-chandrakumar",
        img: "https://iitgn.ac.in/media/pages/faculty/chemistry/fac-chandrakumar/21908591-1679554159/Chandra%20Photo.JPG",
        designation: "Associate Professor",
        dept: "Chemistry",
        email: "a.chandra@iitgn.ac.in",
      },
      {
        name: "Karla Mercado-Shekhar",
        link: "https://iitgn.ac.in/faculty/bioe/fac-karla",
        img: "https://iitgn.ac.in/media/pages/faculty/bioe/fac-karla/2108285146-1679554160/karla.jpg",
        designation: "Assistant Professor",
        dept: "Biological Engineering",
        email: "karlamshekhar@iitgn.ac.in",
        hash: "G86F5Afz3mwv6MtADYQv",
      },
      {
        name: "Himanshu Shekhar",
        link: "https://www.iitgn.ac.in/faculty/ee/fac-himanshu",
        img: "https://www.iitgn.ac.in/media/pages/faculty/ee/fac-himanshu/623112002-1679554160/himanshu.jpg",
        designation: "Assistant Professor",
        dept: "Electrical Engineering",
        email: "himanshu.shekhar@iitgn.ac.in",
      },
      {
        name: "Sivapriya Kirubakaran",
        link: "https://iitgn.ac.in/faculty/chemistry/fac-sivapriya",
        img: "https://iitgn.ac.in/media/pages/faculty/chemistry/fac-sivapriya/556837850-1679554159/sivapriya.png",
        designation: "Associate Professor",
        dept: "Chemistry",
        email: "priyak@iitgn.ac.in",
        hash: "o4DcAf8PEsOilO5i9baY",
      },
      {
        name: "Sudipta Basu",
        link: "https://iitgn.ac.in/faculty/chemistry/fac-sudipta",
        img: "https://iitgn.ac.in/media/pages/faculty/chemistry/fac-sudipta/4089543181-1685686389/sudipta.jpg",
        designation: "Associate Professor",
        dept: "Chemistry",
        email: "sudipta.basu@iitgn.ac.in",
      },
      {
        name: "Sriram Kanvah Gundimeda",
        link: "https://iitgn.ac.in/faculty/chemistry/fac-sriram",
        img: "https://iitgn.ac.in/media/pages/faculty/chemistry/fac-sriram/3485250521-1679554159/sriram.jpg",
        designation: "Associate Professor",
        dept: "Chemistry",
        email: "sriram@iitgn.ac.in",
      },
      {
        name: "Ashutosh Srivastava",
        link: "https://iitgn.ac.in/faculty/bioe/fac-ashutosh",
        img: "https://iitgn.ac.in/media/pages/faculty/bioe/fac-ashutosh/1199779951-1685685814/Ashutosh.jpg",
        designation: "Assistant Professor",
        dept: "Biological Sciences and Engineering",
        email: "ashutosh.s@iitgn.ac.in",
        hash: "66pRjErPQgxIrHmDK6BD",
      },
      {
        name: "Mukesh Dhanka",
        link: "https://iitgn.ac.in/faculty/bioe/fac-mukesh",
        img: "https://iitgn.ac.in/media/pages/faculty/bioe/fac-mukesh/4095272598-1679554160/mukesh.jpg",
        designation: "Assistant Professor",
        dept: "Biological Engineering",
        email: "mukesh.d@iitgn.ac.in",
        hash: "xPqrgxbd0gZ36blzDpL1",
      },
      {
        name: "Nipun Batra",
        link: "https://iitgn.ac.in/faculty/cse/nipun",
        img: "https://iitgn.ac.in/media/pages/faculty/cse/nipun/3587009419-1679554159/nipun.jpg",
        designation: "Assistant Professor",
        dept: "Computer Science & Engineering",
        email: "nipun.batra@iitgn.ac.in",
        hash: "3bfPAe8GjWbOPuh47uCk",
      },
      {
        name: "Vijay Thiruvenkatam",
        link: "https://iitgn.ac.in/faculty/bioe/fac-vijay",
        img: "https://iitgn.ac.in/media/pages/faculty/bioe/fac-vijay/1274823549-1679554160/vijay.jpg",
        designation: "Assistant Research Professor",
        dept: "Biological Engineering",
        email: "vijay@iitgn.ac.in",
        hash: "LK9ZQ6FT9EbYcISOo6Ky",
      },
      {
        name: "Sameer Dalvi",
        link: "https://iitgn.ac.in/hi/faculty/chemical/fac-sameer",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-sameer/1678405332-1679554160/1sameer.jpg",
        designation: "Professor",
        dept: "Chemical Engineering",
        email: "sameervd@iitgn.ac.in",
        hash: "QyWigXd5HhFaeYXMMjIx",
      },
      {
        name: "Biswajit Saha",
        link: "https://iitgn.ac.in/faculty/chemical/fac-biswajit",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-biswajit/377347854-1679554160/saha.png",
        designation: "Assistant Professor",
        dept: "Chemical Engineering",
        email: "bsaha@iitgn.ac.in",
      },
      {
        name: "Yogesh Kumar Meena",
        link: "https://iitgn.ac.in/faculty/cse/yogesh",
        img: "https://iitgn.ac.in/media/pages/faculty/cse/yogesh/2531393478-1684999074/yogesh.webp",
        designation: "Assistant Professor",
        dept: "Computer Science & Engineering",
        email: "yk.meena@iitgn.ac.in",
      },
      {
        name: "Shanmuganathan Raman",
        link: "https://iitgn.ac.in/faculty/cse/shanmuganathan",
        img: "https://iitgn.ac.in/media/pages/faculty/cse/shanmuganathan/1523958848-1679554159/1_shanmuganathan.jpg",
        designation: "Associate Professor",
        dept: "Computer Science & Engineering (Jointly with Electrical Engineering)",
        email: "shanmuga@iitgn.ac.in",
      },
      {
        name: "Dhiraj Bhatia",
        link: "https://iitgn.ac.in/faculty/bioe/fac-dhiraj",
        img: "https://iitgn.ac.in/media/pages/faculty/bioe/fac-dhiraj/396853053-1679554160/dhiraj.JPG",
        designation: "Associate Professor",
        dept: "Biological Engineering",
        email: "dhiraj.bhatia@iitgn.ac.in",
        hash: "hOc8bPcRKSxbzWa9uGsM",
      },
      {
        name: "Kaustubh Rane",
        link: "https://iitgn.ac.in/faculty/chemical/fac-kaustubh",
        img: "https://iitgn.ac.in/media/pages/faculty/chemical/fac-kaustubh/2144754970-1679554160/kaustubh.JPG",
        designation: "Assistant Professor",
        dept: "Chemical Engineering",
        email: "kaustubhrane@iitgn.ac.in",
      },
      {
        name: "Vineet Vashista",
        link: "https://iitgn.ac.in/faculty/me/15-vineet",
        img: "https://iitgn.ac.in/media/pages/faculty/me/15-vineet/3480943111-1679554160/vineet.JPG",
        designation: "Associate Professor",
        dept: "Mechanical Engineering",
        email: "vineet.vashista@iitgn.ac.in",
      },
      {
        name: "Abhijit Mishra",
        link: "https://iitgn.ac.in/faculty/mse/fac-abhijit",
        img: "https://iitgn.ac.in/media/pages/faculty/mse/fac-abhijit/4076577973-1679554159/abhijit.jpg",
        designation: "Associate Professor",
        dept: "Materials Engineering",
        email: "amishra@iitgn.ac.in",
        hash: "yEj2mQyPcznq1nFu04gU",
      },
      {
        name: "Sairam S. Mallajosyula",
        link: "https://iitgn.ac.in/faculty/chemistry/fac-sairam",
        img: "https://iitgn.ac.in/media/pages/faculty/chemistry/fac-sairam/1525796205-1679554159/sairam.jpg",
        designation: "Associate Professor",
        dept: "Chemistry",
        email: "msairam@iitgn.ac.in",
        hash: "o2WY8IT3dYl8ePEnfFxC",
      },
      {
        name: "Krishna Kanti Dey",
        link: "https://iitgn.ac.in/faculty/phy/fac-krishna",
        img: "https://iitgn.ac.in/media/pages/faculty/phy/fac-krishna/1778184909-1679554160/Krishna.jpg",
        designation: "Assistant Professor",
        dept: "Physics",
        email: "k.dey@iitgn.ac.in",
        hash: "HiJQX1sEouWkSJVHuC5W",
      },
      {
        name: "Superb Misra",
        link: "https://iitgn.ac.in/faculty/mse/fac-superb",
        img: "https://iitgn.ac.in/media/pages/faculty/mse/fac-superb/1833087412-1687604907/superb.jpg",
        designation: "Associate Professor",
        dept: "Materials Engineering",
        email: "smisra@iitgn.ac.in",
      },
      {
        name: "Sharad Gupta",
        link: "https://iitgn.ac.in/faculty/bioe/fac-sharad",
        img: "https://iitgn.ac.in/media/pages/faculty/bioe/fac-sharad/682033906-1685685855/sharad.jpg",
        designation: "Associate Professor",
        dept: "Biological Engineering",
        email: "sharad@iitgn.ac.in",
        hash: "opHQ6d54TvlR9EBbMi5K",
      },
      {
        name: "Bhaskar Datta",
        link: "https://iitgn.ac.in/faculty/bioe/fac-bhaskar",
        img: "https://iitgn.ac.in/media/pages/faculty/bioe/fac-bhaskar/1847654198-1679554160/bhaskar.JPG",
        designation: "Associate Professor",
        dept: "Biological Sciences and Engineering (Jointly with Chemistry)",
        email: "bdatta@iitgn.ac.in",
      },
    ],
  },
];
