import bio from "../imgs/bio.png";
import man from "../imgs/man.png";
import ene from "../imgs/energy.png";
import ai from "../imgs/ai.png";
import food from "../imgs/food.png";
import def from "../imgs/def.png";
import pharma from "../imgs/pharma.png";
import climate from "../imgs/climate.png";
export const cardVar = [
  {
    label: "Bioengineering, Healthcare, Pharma",
    bg: "hover:from-cyan-400 hover:to-blue-300",
    img: bio,
    prof: [
      {
        name: "Dhiraj Bhatia",
        link: "https://iitgn.ac.in/faculty/bioe/fac-dhiraj",
        img: "https://iitgn.ac.in/media/pages/faculty/bioe/fac-dhiraj/396853053-1679554160/dhiraj.JPG",
        designation: "Associate Professor",
        dept: "Biological Engineering",
        email: "dhiraj.bhatia@iitgn.ac.in",
      },
      {
        name: "Jhuma Saha",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Electrical Engineering",
        email: "jhuma.saha@iitgn.ac.in",
      },
      {
        name: "Sharad Gupta",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Biological Engineering",
        email: "sharad@iitgn.ac.in",
      },
      {
        name: "Himanshu Shekhar",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Electrical Engineering",
        email: "himanshu.shekhar@iitgn.ac.in",
      },
      {
        name: "Prachi Thareja",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Chemical Engineering",
        email: "prachi@iitgn.ac.in",
      },
      {
        name: "Pratik Mutha",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Biological Engineering",
        email: "pm@iitgn.ac.in",
      },
      {
        name: "Sameer Dalvi",
        link: "",
        img: "",
        designation: "Professor",
        dept: "",
        email: "sameervd@iitgn.ac.in",
      },
      {
        name: "Abhijit Mishra",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Materials Engineering",
        email: "amishra@iitgn.ac.in",
      },
      {
        name: "Krishna Kanti Dey",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Physics",
        email: "k.dey@iitgn.ac.in",
      },
      {
        name: "Mithun Radhakrishnan",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Chemical Engineering",
        email: "mithunr@iitgn.ac.in",
      },
    ],
  },
  {
    label: "Manufacturing",
    bg: "hover:from-fuchsia-300 hover:to-purple-400",
    img: man,
    prof: [
      {
        name: "Kaustubh Rane",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Chemical Engineering",
        email: "kaustubhrane@iitgn.ac.in",
      },
      {
        name: "Madhu Vadali",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Electrical Engineering (Jointly with Mechanical Engineering)",
        email: "madhu.vadali@iitgn.ac.in",
      },
      {
        name: "Hari Ganesh ",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Chemical Engineering",
        email: "hariganesh@iitgn.ac.in",
      },
      {
        name: "Pradipta Ghosh",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Materials Engineering",
        email: "pradipta.ghosh@iitgn.ac.in",
      },
      {
        name: "Raghavan Ranganathan",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Materials Engineering",
        email: "rraghav@iitgn.ac.in",
      },
      {
        name: "Chinmay Ghoroi",
        link: "",
        img: "",
        designation: "Professor",
        dept: "Chemical Engineering",
        email: "chinmayghoroi@gmail.com",
      },
      {
        name: "Superb Misra",
        link: "",
        img: "",
        designation: "Associate Professo",
        dept: "Materials Engineering",
        email: "smisra@iitgn.ac.in",
      },
      {
        name: "Emila Panda",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Materials Engineering",
        email: "emila@iitgn.ac.in",
      },
      {
        name: "Ravi Sastri Ayyagari",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Mechanical Engineering",
        email: "ravi.ayyagari@iitgn.ac.in",
      },
      {
        name: "Chandan Misra",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Physics",
        email: "chandan.mishra@iitgn.ac.in",
      },
      {
        name: "Pratyush Dayal",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Chemical Engineering",
        email: "pdayal@iitgn.ac.in",
      },
      {
        name: "Abhay Raj Singh Gautam",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Materials Engineering",
        email: "agautam@iitgn.ac.in",
      },
      {
        name: "Nihar Ranjan Mohapatra",
        link: "",
        img: "",
        designation: "Professor",
        dept: "Electrical Engineering",
        email: "nihar@iitgn.ac.in",
      },
      {
        name: "Sandeep Lashkare",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Electrical Engineering",
        email: "sandip.lashkare@iitgn.ac.in",
      },
    ],
  },
  {
    label: "Energy and Water",
    bg: "hover:from-green-400 hover:to-cyan-300",
    img: ene,
    prof: [
      {
        name: "Atul Bhargav",
        link: "",
        img: "",
        designation: "Professor",
        dept: "Mechanical Engineering",
        email: "atul.bhargav@iitgn.ac.in",
      },
      {
        name: "Soumyadip Sett",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Mechanical Engineering",
        email: "soumyadipsett@iitgn.ac.in",
      },
      {
        name: "Sriharitha Rowthu",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Materials Engineering",
        email: "sriharitha.rowthu@iitgn.ac.in",
      },
      {
        name: "Gopinadhan Kalon",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Materials Engineering & Physics",
        email: "gopinadhan.kalon@iitgn.ac.in",
      },
      {
        name: "Sudhanshu Sharma",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Chemistry",
        email: "ssharma@iitgn.ac.in",
      },
      {
        name: "Naran M Pindoriya",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Electrical Engineering",
        email: "naran@iitgn.ac.in",
      },
      {
        name: "Saumyakanti Khatua",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Chemistry",
        email: "khatuask@iitgn.ac.in",
      },
      {
        name: "Pallavi Bharadwaj",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Electrical Engineering",
        email: "pallavib@iitgn.ac.in",
      },
      {
        name: "Ragavan K",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Electrical Engineering",
        email: "ragavan@iitgn.ac.in",
      },
      {
        name: "Ravi Hegde",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Electrical Engineering",
        email: "hegder@iitgn.ac.in",
      },
      {
        name: "Tarun Agrawal",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Electrical Engineering",
        email: "tagarwal@iitgn.ac.in",
      },
      {
        name: "Abinaya Sampat (lead)",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Chemical Engineering",
        email: "abinaya.sampath@iitgn.ac.in",
      },
    ],
  },
  {
    label: "AI and Computing",
    bg: "hover:from-purple-300 hover:to-indigo-300",
    img: ai,
    prof: [
      {
        name: "Shanmuganathan Raman",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Computer Science & Engineering (Jointly with Electrical Engineering)",
        email: "shanmuga@iitgn.ac.in",
      },
      {
        name: "Mayank Singh",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Computer Science & Engineering",
        email: "singh.mayank@iitgn.ac.in",
      },
      {
        name: "Yogesh Kumar Meena",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Computer Science & Engineering",
        email: "yk.meena@iitgn.ac.in",
      },
      {
        name: "Ashutosh Srivastava",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Biological Sciences and Engineering",
        email: "ashutosh.s@iitgn.ac.in",
      },
      {
        name: "Anirban Mondal",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Chemistry",
        email: "amondal@iitgn.ac.in",
      },
      {
        name: "Rajat Moona",
        link: "",
        img: "",
        designation: "Professor",
        dept: "Computer Science & Engineering",
        email: "moona@iitgn.ac.in",
      },
      {
        name: "Neeldhara Misra",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Computer Science & Engineering",
        email: "neeldhara.m@iitgn.ac.in",
      },
      {
        name: "Anirban Dasgupta",
        link: "",
        img: "",
        designation: "Professor",
        dept: "Computer Science & Engineering",
        email: "anirbandg@iitgn.ac.in",
      },
      {
        name: "Nipun Batra",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Computer Science & Engineering",
        email: "nipun.batra@iitgn.ac.in",
      },
      {
        name: "Manoj Gupta",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Computer Science & Engineering",
        email: "gmanoj@iitgn.ac.in",
      },
      {
        name: "Krishna Miyapuram",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Cognitive and Brain Sciences",
        email: "kprasad@iitgn.ac.in",
      },
      {
        name: "Uttama Lahiri",
        link: "",
        img: "",
        designation: "Professor",
        dept: "Electrical Engineering",
        email: "uttamalahiri@iitgn.ac.in",
      },
      {
        name: "Sushobhan Sen",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Civil Engineering",
        email: "sushobhan.sen@iitgn.ac.in",
      },
      {
        name: "Abhishek Bhicchawat",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Computer Science & Engineering",
        email: "abhishek.b@iitgn.ac.in",
      },
      {
        name: "Sandeep Lashkare",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Electrical Engineering",
        email: "sandip.lashkare@iitgn.ac.in",
      },
    ],
  },
  {
    label: "Agro and Food processing",
    bg: "hover:from-yellow-400 hover:to-orange-300",
    img: food,
    prof: [
      {
        name: "Subramanian Sankaranarayana",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Biological Sciences and Engineering",
        email: "s.sankar@iitgn.ac.in",
      },
      {
        name: "Bhaskar Dattta",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Biological Sciences and Engineering (Jointly with Chemistry)",
        email: "bdatta@iitgn.ac.in",
      },
      {
        name: "Prachi Thareja",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Chemical Engineering",
        email: "prachi@iitgn.ac.in",
      },
      {
        name: "Souymadip Sett",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Mechanical Engineering",
        email: "soumyadipsett@iitgn.ac.in",
      },
      {
        name: "Kabeer Jasuja",
        link: "",
        img: "",
        designation: "Professor",
        dept: "Chemical Engineering",
        email: "kabeer@iitgn.ac.in",
      },
      {
        name: "Biswajit Saha",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Chemical Engineering",
        email: "bsaha@iitgn.ac.in",
      },
    ],
  },
  {
    label: "Defence, Military & Space Technology ",
    bg: "hover:from-pink-300 hover:to-rose-300",
    img: def,
    prof: [
      {
        name: "Biswajit Saha ",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Chemical Engineering",
        email: "bsaha@iitgn.ac.in",
      },
      {
        name: "Kabeer Jasuja (lead)",
        link: "",
        img: "",
        designation: "Professor",
        dept: "Chemical Engineering",
        email: "kabeer@iitgn.ac.in",
      },
      {
        name: "Vineet Vashista ",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Mechanical Engineering",
        email: "vineet.vashista@iitgn.ac.in",
      },
      {
        name: "Harish P M",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Mechanical Engineering",
        email: "harish@iitgn.ac.in",
      },
      {
        name: "Arup Lal Chakraborty",
        link: "",
        img: "",
        designation: "Professor",
        dept: "Electrical Engineering",
        email: "arup@iitgn.ac.in",
      },
      {
        name: "Manish Kumar",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Civil Engineering",
        email: "mkumar@iitgn.ac.in",
      },
      {
        name: "Nithin George",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Electrical Engineering",
        email: "nithin@iitgn.ac.in",
      },
      {
        name: "Dilip Sundaram",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Mechanical Engineering",
        email: "dilip.sundaram@iitgn.ac.in",
      },
      {
        name: "Joycee Mekie",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Electrical Engineering",
        email: "joycee@iitgn.ac.in",
      },
      {
        name: "Nihar Ranjan Mohapatra",
        link: "",
        img: "",
        designation: "Professor",
        dept: "Electrical Engineering",
        email: "nihar@iitgn.ac.in",
      },
      {
        name: "Pratyush Dayal",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Chemical Engineering",
        email: "pdayal@iitgn.ac.in",
      },
      {
        name: "Vinod Narayan",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Mechanical Engineering",
        email: "vinod@iitgn.ac.in",
      },
    ],
  },
  {
    label: "Climate Challange & Solutions",
    bg: "hover:from-blue-400 hover:to-indigo-300",
    img: climate,
    prof: [
      {
        name: "Utsav Mannu",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Earth Sciences",
        email: "utsav.mannu@iitgn.ac.in",
      },
      {
        name: "Vimal Mishra",
        link: "",
        img: "",
        designation: "Professor",
        dept: "Civil Engineering and Earth Sciences",
        email: "vmishra@iitgn.ac.in",
      },
      {
        name: "Pankaj Khanna",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Earth Sciences",
        email: "pankaj.khanna@iitgn.ac.in",
      },
      {
        name: "Udit Bhatia (lead)",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Civil Engineering",
        email: "bhatia.u@iitgn.ac.in",
      },
      {
        name: "Gaurav Srivastava",
        link: "",
        img: "",
        designation: "Professor",
        dept: "Civil Engineering",
        email: "gauravs@iitgn.ac.in",
      },
      {
        name: "Vikrant Jain",
        link: "",
        img: "",
        designation: "Professor",
        dept: "Earth Sciences",
        email: "vjain@iitgn.ac.in",
      },
      {
        name: "Amit Prashant",
        link: "",
        img: "",
        designation: "Professor",
        dept: "Civil Engineering",
        email: "ap@iitgn.ac.in",
      },
      {
        name: "Sameer Patel",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Civil Engineering (Jointly with Chemical Engineering)",
        email: "sameer.patel@iitgn.ac.in",
      },
    ],
  },
  {
    label: "Pharma and Healthcare",
    bg: "hover:from-cyan-400  hover:to-blue-500",
    img: pharma,
    prof: [
      {
        name: "Uttama Lahiri",
        link: "",
        img: "",
        designation: "Professor",
        dept: "Electrical Engineering",
        email: "uttamalahiri@iitgn.ac.in",
      },
      {
        name: "Iti Gupta",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Chemistry",
        email: "uttamalahiri@iitgn.ac.in",
      },
      {
        name: "Chandrakumar Appayee",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Chemistry",
        email: "a.chandra@iitgn.ac.in",
      },
      {
        name: "Sairam",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Chemistry",
        email: "msairam@iitgn.ac.in",
      },
      {
        name: "Karla Mercado-Shekhar",
        link: "",
        img: "",
        designation: "Assistant Professor",
        dept: "Biological Engineering",
        email: "karlamshekhar@iitgn.ac.in",
      },
      {
        name: "Sivapriya Kirubakaran",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Chemistry",
        email: "priyak@iitgn.ac.in",
      },
      {
        name: "Sudipta Basu",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Chemistry",
        email: "sudipta.basu@iitgn.ac.in",
      },
      {
        name: "Sriram Kanvah",
        link: "",
        img: "",
        designation: "Associate Professor",
        dept: "Chemistry",
        email: "sriram@iitgn.ac.in",
      },
    ],
  },
];
