import bio from "../imgs/bio.png";
import man from "../imgs/man.png";
import ene from "../imgs/energy.png";
import ai from "../imgs/ai.png";
import food from "../imgs/food.png";
import def from "../imgs/def.png";
import pharma from "../imgs/pharma.png";
import climate from "../imgs/climate.png";
export const cardVar = [
  {
    label: "Bioengineering, Healthcare, Pharma",
    bg: "hover:from-cyan-400 hover:to-blue-300",
    img: bio,
    prof: [
      {
        name: "Dhiraj Bhatia",
        link: "https://iitgn.ac.in/faculty/bioe/fac-dhiraj",
        img: "https://iitgn.ac.in/media/pages/faculty/bioe/fac-dhiraj/396853053-1679554160/dhiraj.JPG",
        designation: "Associate Professor",
        dept: "Biological Engineering",
        email: "dhiraj.bhatia@iitgn.ac.in",
      },
      {
        name: "Jhuma Saha ",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Sharad Gupta",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Himanshu",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Karla",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Prachi Thareja",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Pratik Mutha",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Sameer Dalvi",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Abhijit Mishra",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Krishna Kanti Dey",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Mithun Radhakrishnan",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Bhaskar Dutta",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
    ],
  },
  {
    label: "Manufacturing",
    bg: "hover:from-fuchsia-300 hover:to-purple-400",
    img: man,
    prof: [
      {
        name: "Madhu Vadali (lead)",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Hari Ganesh ",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Pradipta Ghosh",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Raghavan Ranganathan",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Chinmay Ghoroi",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Superb Misra",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Emila Panda",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Ravi Shashtri",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Amit Arora",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Chandan Misra",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Pratyush Dayal",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Prachi Thareja",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Tarun Agarwal",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Sandeep Lashkare",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
    ],
  },
  {
    label: "Energy and Water",
    bg: "hover:from-green-400 hover:to-cyan-300",
    img: ene,
    prof: [
      {
        name: "Atul Bhargav",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Soumyadip Sett",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Sriharitha Rowthu",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Gopinadhan Kalon",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Sudhanshu Sharma",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Naran M Pindoriya",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Saumyakanti Khatua",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Pallavi Bharadwaj",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Raghavan (elec)",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Ravi Hegde",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Tarun Agrawal",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Abinaya Sampat (lead)",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Sameer Patel",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
    ],
  },
  {
    label: "AI and Computing",
    bg: "hover:from-purple-300 hover:to-indigo-300",
    img: ai,
    prof: [
      {
        name: "Shanmuganathan Raman",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Mayank Singh",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Yogesh Kumar Meena",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Ashutosh Srivastava",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Anirban Mondal",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Rajat Moona",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Neeldhara (lead)",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Anirban Dasgupta",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Nipun Batra",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Manoj Gupta",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Krishna Miyapuram",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Uttama Lahiri",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Sushoban",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Joycee",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Dilip Sundaram",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
    ],
  },
  {
    label: "Agro and Food processing",
    bg: "hover:from-yellow-400 hover:to-orange-300",
    img: food,
    prof: [
      {
        name: "Subramanian Sankaranarayana",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Bhaskar Dattta",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Prachi Thareja",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Souymadip Sett",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Kabeer Jasuja",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Biswajeet Saha",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
    ],
  },
  {
    label: "Defence, Military & Space Technology ",
    bg: "hover:from-pink-300 hover:to-rose-300",
    img: def,
    prof: [
      {
        name: "Biswajit Saha ",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Kabeer Jasuja (lead)",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Vineet Vashista ",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Harish P M",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Arup Lal Chakraborty",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Manish Kumar",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Nithin George",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Dilip Sundaram",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Joycee",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Nihar Ranjan",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Pratyush Dayal",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Vinod Narayan",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
    ],
  },
  {
    label: "Climate Challange & Solutions",
    bg: "hover:from-blue-400 hover:to-indigo-300",
    img: climate,
    prof: [
      {
        name: "Utsav Mannu",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Vimal Mishra",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Pankaj Khanna",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Udit Bhatia (lead)",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Gaurav Srivastava",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Vikrant Jain",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Amit Prashant",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Sameer Patel",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
    ],
  },
  {
    label: "Pharma and Healthcare",
    bg: "hover:from-cyan-400  hover:to-blue-500",
    img: pharma,
    prof: [
      {
        name: "Uttama Lahiri",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Iti Gupta",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Chandrakumar Appayee",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Sairam",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Himanshu & Karla",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Sivapriya (lead)",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Sudipta Basu",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
      {
        name: "Sriram Kanvah",
        link: "",
        img: "",
        designation: "",
        dept: "",
        email: "",
      },
    ],
  },
];
